  MODULE('EXISTENCIAS002.CLW')
BrowseTanques_plantas  PROCEDURE                      !Tanques_plantas
BrowseMediciones       PROCEDURE                      !Mediciones
BrowsePresiones_corregidas PROCEDURE                  !Presiones_corregidas
BrowseLocalidades_GLP  PROCEDURE                      !Localidades_GLP
UpdateProveedores      PROCEDURE                      !Form Proveedores
UpdateTransportistas   PROCEDURE                      !Form Transportistas
SelectLocalidades_GLP  PROCEDURE                      !Seleccionar un registro de Localidades_GLP
UpdatePlantas          PROCEDURE                      !Form Plantas
SelectPlantas          PROCEDURE                      !Seleccionar un registro de Plantas
  END
