  MODULE('EXISTENCIAS001.CLW')
BrowseProveedores      PROCEDURE                      !Proveedores
BrowseTransportistas   PROCEDURE                      !Transportistas
BrowsePlantas          PROCEDURE                      !Plantas
BrowseDescargas        PROCEDURE
BrowseViajes           PROCEDURE                      !Viajes
BrowseDensidades_Corregidas PROCEDURE                 !Densidades_Corregidas
BrowseNiveles_Volumenes PROCEDURE                     !Niveles_Volumenes
Browset_tanques        PROCEDURE                      !t_tanques
  END
