  MODULE('EXISTENCIAS011.CLW')
ConciliacionRemitos    PROCEDURE
selectFacturas         PROCEDURE                      !comprobantes
SelectProveedorContable PROCEDURE                     !Proveedores_contable
updateCostosGLP        PROCEDURE                      !Formulario Costos_GLP
SelectViajesDescargados PROCEDURE
GraficoExistencia      PROCEDURE
ReportMediciones       PROCEDURE(STRING,STRING)
  END
