  MODULE('EXISTENCIAS005.CLW')
UpdateProcedencias     PROCEDURE                      !Form Procedencias
BrowseProgramacion     PROCEDURE                      !programacion
UpdateProgramacion     PROCEDURE                      !Form programacion
SelectViajesEnTransito PROCEDURE                      !Seleccionar un registro de Viajes
SelectProcedencias     PROCEDURE                      !Procedencias
BrowseParametros       PROCEDURE                      !parametros
UpdateParametros       PROCEDURE                      !Form parametros
updateMedicionesExistencias PROCEDURE(LONG,LONG,LONG) !Form Mediciones
  END
