  MODULE('EXISTENCIAS009.CLW')
BrowseConceptosAduana  PROCEDURE
UpdateConceptosAduana  PROCEDURE                      !Form conceptos_anticipos
BrowseDespachoAduanero PROCEDURE
SelectDespachantes     PROCEDURE                      !Select a Despachantes Record
UpdateDespachoAduanero PROCEDURE                      !Form Despacho_aduana
BrowseDespachantes     PROCEDURE
UpdateDespachantes     PROCEDURE                      !Form Despachantes
SelectViajesDespacho   PROCEDURE
UpdateDespachoConceptos PROCEDURE                     !Form Despacho_conceptos
ReportDespachoAduanero PROCEDURE                      !Report the Despacho_aduana File
  END
