  MODULE('EXISTENCIAS006.CLW')
SelectProgramacion     PROCEDURE                      !Browse the programacion file
BrowseExistencias      PROCEDURE                      !Browse the Existencias file
UpdateExistencias      PROCEDURE                      !Form Existencias
BrowseGeneracionSolicitudAnticipo PROCEDURE           !Browse the Viajes file
ReportSolicitudAnticipo PROCEDURE(STRING,STRING)
  END
