  MODULE('EXISTENCIAS008.CLW')
totalesProductoLocalidad PROCEDURE
ReportExistencias_2    PROCEDURE(STRING,STRING)       !Report the Existencias File
BrowseViajesenProceso  PROCEDURE                      !Viajes
UpdateViajesenProceso  PROCEDURE                      !Form Viajes
BrowseContactos        PROCEDURE
UpdateContactos        PROCEDURE                      !Form contactos
ReportProveedores      PROCEDURE
UpdateContactosTransportista PROCEDURE
SelectLocalidades_GLPAlias PROCEDURE
  END
