  MODULE('EXISTENCIAS007.CLW')
BrowseBalanceProducto  PROCEDURE                      !Browse the Viajes file
ReportBalanceProducto  PROCEDURE(STRING,STRING)
BrowseAnticiposGenerados PROCEDURE
SelectLocalidadGlobal  PROCEDURE
ReportExistencias      PROCEDURE(STRING,STRING)       !Report the Existencias File
UpdateViajesAnticipos  PROCEDURE                      !Form viajes_anticipos
SelectExistencias      PROCEDURE
  END
