  MODULE('EXISTENCIAS003.CLW')
UpdateDescargas        PROCEDURE                      !Form Descargas
SelectTransportistas   PROCEDURE                      !Seleccionar un registro de Transportistas
SelectProveedores      PROCEDURE                      !Seleccionar un registro de Proveedores
UpdateViajes           PROCEDURE                      !Form Viajes
UpdateDensidades_Corregidas PROCEDURE                 !Form Densidades_Corregidas
Selectt_tanques        PROCEDURE                      !Seleccionar un registro de t_tanques
UpdateNiveles_Volumenes PROCEDURE                     !Form Niveles_Volumenes
Updatet_tanques        PROCEDURE                      !Form t_tanques
UpdateTanques_plantas  PROCEDURE(long)                !Form Tanques_plantas
  END
